### ISSUE TITLE
Crash at boot

### ISSUE THREAD

**Issue by LemADEC** [PrinceOfAmber/RootsClassic#12]
As of RootsClassic-1.12.2-1.1.0.jar, game crashes at boot:

```
java.lang.IllegalArgumentException: Duplicate ingredients are not allowed for incoming ritual : vacuumStoneCrafting and existing ritual growerStoneCrafting
    at elucent.rootsclassic.ritual.RitualManager.addRitual(RitualManager.java:68)
    at elucent.rootsclassic.ritual.RitualManager.init(RitualManager.java:403)
    at elucent.rootsclassic.RegistryManager.onRegisterRecipeEvent(RegistryManager.java:191)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1152_RegistryManager_onRegisterRecipeEvent_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3927)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Deleting rootsclassic.cfg didn't help

**Comment by SihenZhang** [comment]
The same crash happened to me, too. Here is the crash report. 
https://pastebin.com/7VQaRqie

**Comment by Sunconure11** [comment]
Can confirm the same issue.

https://pastebin.com/jxgrGZCT

**Comment by PrinceOfAmber** [comment]
I will have a hotfix out within the hour

**Comment by PrinceOfAmber** [comment]
its uploaded to curse, so whenever they approve the file https://minecraft.curseforge.com/projects/roots-classic/files/2599066
